apiVersion: apps/v1

# SETS UP DEPLOMENT OBJECT
kind: Deployment
metadata:
  name: pylogix-as-service-deployment

spec:
  # SETS HOW MANY INSTANCES
  replicas: 1

  # SELECTS PODS TO BE CONTROLLED
  selector:
    matchLabels:
      app: pylogix-as-service

  # SETUP INDIVIDUAL PODS
  template:
    metadata:
      labels:
        app: pylogix-as-service
    spec:
      containers:
      - name: pylogix-as-service
        image: localhost:32000/pylogix-as-service:v1
        args: ["--server-address", "0.0.0.0", "--server-port", "7777", "--simulate", "True"]
        ports:
        - containerPort: 7777
